-- ===============================================================
-- EXAMEN FINAL BASE DE DATOS - CRISTALERÍA ANDINA S.A.
-- Autor: Bastián Valdivia
-- ===============================================================


BEGIN
   FOR t IN (SELECT table_name FROM user_tables) LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
   EXECUTE IMMEDIATE 'PURGE RECYCLEBIN';
END;
/
-- =====================
-- TABLAS PRINCIPALES
-- =====================

CREATE TABLE REGION (
    id_region NUMBER PRIMARY KEY,
    nombre VARCHAR2(50) UNIQUE NOT NULL
);

CREATE SEQUENCE SEQ_REGION
START WITH 21
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE COMUNA (
    id_comuna NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1050 INCREMENT BY 5),
    nombre VARCHAR2(50) NOT NULL,
    id_region NUMBER NOT NULL,
    CONSTRAINT pk_comuna PRIMARY KEY (id_comuna),
    CONSTRAINT fk_comuna_region FOREIGN KEY (id_region) REFERENCES REGION(id_region)
);

CREATE TABLE PLANTA (
    id_planta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(80) NOT NULL,
    direccion VARCHAR2(120),
    id_comuna NUMBER NOT NULL,
    CONSTRAINT fk_planta_comuna FOREIGN KEY (id_comuna) REFERENCES COMUNA(id_comuna)
);

CREATE TABLE EMPLEADO (
    id_empleado NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rut VARCHAR2(12) UNIQUE NOT NULL,
    nombres VARCHAR2(80) NOT NULL,
    apellidos VARCHAR2(80) NOT NULL,
    fecha_contratacion DATE,
    sueldo_base NUMBER(10,2),
    estado_activo CHAR(1) CHECK (estado_activo IN ('S','N')),
    id_planta NUMBER NOT NULL,
    afp VARCHAR2(50),
    salud VARCHAR2(50),
    id_jefe NUMBER,
    CONSTRAINT fk_empleado_planta FOREIGN KEY (id_planta) REFERENCES PLANTA(id_planta),
    CONSTRAINT fk_empleado_jefe FOREIGN KEY (id_jefe) REFERENCES EMPLEADO(id_empleado)
);

CREATE TABLE TIPO_MAQUINA (
    id_tipo_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL
);

CREATE TABLE MAQUINA (
    id_maquina NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_maquina VARCHAR2(20) NOT NULL,
    nombre VARCHAR2(80),
    estado_activo CHAR(1) CHECK (estado_activo IN ('S','N')),
    id_planta NUMBER NOT NULL,
    id_tipo_maquina NUMBER NOT NULL,
    CONSTRAINT fk_maquina_planta FOREIGN KEY (id_planta) REFERENCES PLANTA(id_planta),
    CONSTRAINT fk_maquina_tipo FOREIGN KEY (id_tipo_maquina) REFERENCES TIPO_MAQUINA(id_tipo_maquina)
);

CREATE TABLE TURNO (
    id_turno NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(50) NOT NULL,
    hora_inicio VARCHAR2(5),
    hora_fin VARCHAR2(5)
);

CREATE TABLE ORDEN_MANTENCION (
    id_orden NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_maquina NUMBER NOT NULL,
    id_tecnico NUMBER NOT NULL,
    fecha_programada DATE,
    fecha_ejecucion DATE,
    descripcion VARCHAR2(255),
    CONSTRAINT fk_orden_maquina FOREIGN KEY (id_maquina) REFERENCES MAQUINA(id_maquina),
    CONSTRAINT fk_orden_tecnico FOREIGN KEY (id_tecnico) REFERENCES EMPLEADO(id_empleado),
    CONSTRAINT chk_fechas CHECK (fecha_ejecucion >= fecha_programada)
);

CREATE TABLE ASIGNACION_TURNO (
    id_asignacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE,
    id_empleado NUMBER NOT NULL,
    id_turno NUMBER NOT NULL,
    id_maquina NUMBER,
    rol VARCHAR2(50),
    CONSTRAINT fk_asig_empleado FOREIGN KEY (id_empleado) REFERENCES EMPLEADO(id_empleado),
    CONSTRAINT fk_asig_turno FOREIGN KEY (id_turno) REFERENCES TURNO(id_turno),
    CONSTRAINT fk_asig_maquina FOREIGN KEY (id_maquina) REFERENCES MAQUINA(id_maquina)
);

-- ===============================================================
-- POBLAMIENTO DE TABLAS
-- ===============================================================

-- REGIÓN
INSERT INTO REGION VALUES (SEQ_REGION.NEXTVAL, 'Metropolitana');
INSERT INTO REGION VALUES (SEQ_REGION.NEXTVAL, 'Valparaíso');

-- COMUNA
INSERT INTO COMUNA (nombre, id_region) VALUES ('Santiago', 21);
INSERT INTO COMUNA (nombre, id_region) VALUES ('Puente Alto', 21);
INSERT INTO COMUNA (nombre, id_region) VALUES ('Viña del Mar', 22);
INSERT INTO COMUNA (nombre, id_region) VALUES ('Quilpué', 22);

-- PLANTA
INSERT INTO PLANTA (nombre, direccion, id_comuna)
VALUES ('Planta Central', 'Av. Cristal 1234, Santiago', 1050);
INSERT INTO PLANTA (nombre, direccion, id_comuna)
VALUES ('Planta Costa', 'Camino Fusión 456, Viña del Mar', 1060);

-- EMPLEADO
INSERT INTO EMPLEADO (rut, nombres, apellidos, fecha_contratacion, sueldo_base, estado_activo, id_planta, afp, salud)
VALUES ('12.345.678-9', 'Carlos', 'Ramírez', TO_DATE('2020-01-10','YYYY-MM-DD'), 850000, 'S', 1, 'Provida', 'Fonasa');

INSERT INTO EMPLEADO (rut, nombres, apellidos, fecha_contratacion, sueldo_base, estado_activo, id_planta, afp, salud, id_jefe)
VALUES ('16.789.345-0', 'Andrea', 'Gómez', TO_DATE('2021-04-02','YYYY-MM-DD'), 680000, 'S', 1, 'Habitat', 'Banmédica', 1);

-- TIPO DE MÁQUINA
INSERT INTO TIPO_MAQUINA (nombre) VALUES ('Cortadora de Vidrio');
INSERT INTO TIPO_MAQUINA (nombre) VALUES ('Horno de Fusión');

-- MÁQUINA
INSERT INTO MAQUINA (numero_maquina, nombre, estado_activo, id_planta, id_tipo_maquina)
VALUES ('M-001', 'Cortadora 1', 'S', 1, 1);
INSERT INTO MAQUINA (numero_maquina, nombre, estado_activo, id_planta, id_tipo_maquina)
VALUES ('M-002', 'Horno Alpha', 'S', 2, 2);

-- TURNO
INSERT INTO TURNO (nombre, hora_inicio, hora_fin)
VALUES ('Mañana', '06:00', '14:00');
INSERT INTO TURNO (nombre, hora_inicio, hora_fin)
VALUES ('Tarde', '14:00', '22:00');
INSERT INTO TURNO (nombre, hora_inicio, hora_fin)
VALUES ('Noche', '22:00', '06:00');

COMMIT;

-- ===============================================================
-- CONSULTAS (INFORMES)
-- ===============================================================

-- Informe 1: Turnos con hora_inicio posterior a las 20:00
PROMPT === INFORME 1: Turnos Nocturnos ===
SELECT nombre AS TURNO, hora_inicio AS ENTRADA, hora_fin AS SALIDA
FROM TURNO
WHERE hora_inicio > '20:00'
ORDER BY hora_inicio DESC;

-- Informe 2: Turnos diurnos entre 06:00 y 14:59
PROMPT === INFORME 2: Turnos Diurnos ===
SELECT nombre AS TURNO, hora_inicio AS ENTRADA, hora_fin AS SALIDA
FROM TURNO
WHERE hora_inicio BETWEEN '06:00' AND '14:59'
ORDER BY hora_inicio ASC;

COMMIT;

-- ===============================================================
-- FIN DEL EXAMEN FINAL - CRISTALERÍA ANDINA S.A.
-- ===============================================================