-- =========================================================
-- PRY2204_S8 — Script Final (Entrega)
-- Alumno : Bastián Valdivia
-- Nota: Ejecutar BLOQUE POR BLOQUE (Ctrl+Enter / F5 por sección)
-- El script es idempotente: crea/ajusta solo si falta.
-- =========================================================

----------------------------------------------------------------
-- 0) TABLAS BASE DEL MODELO — CREA SOLO SI NO EXISTEN
----------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE '
CREATE TABLE cliente (
  id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(80) NOT NULL,
  telefono VARCHAR2(20),
  email VARCHAR2(100),
  id_region NUMBER,
  CONSTRAINT fk_cliente_region FOREIGN KEY (id_region)
    REFERENCES region(id_region)
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE proveedor (
  id_proveedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  telefono VARCHAR2(20),
  email VARCHAR2(100) UNIQUE
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE marca (
  id_marca NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(60) NOT NULL UNIQUE
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE producto (
  id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  precio NUMBER(10,0) CHECK (precio > 0),
  stock_min NUMBER(5) DEFAULT 3 CHECK (stock_min >= 3),
  id_marca NUMBER,
  id_proveedor NUMBER,
  CONSTRAINT fk_prod_marca FOREIGN KEY (id_marca)
    REFERENCES marca(id_marca),
  CONSTRAINT fk_prod_prov FOREIGN KEY (id_proveedor)
    REFERENCES proveedor(id_proveedor)
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE vendedor (
  id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(80) NOT NULL,
  comision NUMBER(4,2) DEFAULT 0 CHECK (comision BETWEEN 0 AND 0.25)
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE medio_pago (
  id_medio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(50) NOT NULL UNIQUE
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE venta (
  id_venta NUMBER PRIMARY KEY,
  fecha_venta DATE DEFAULT SYSDATE,
  id_cliente NUMBER,
  id_vendedor NUMBER,
  id_medio NUMBER,
  total NUMBER(10,0),
  CONSTRAINT fk_venta_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
  CONSTRAINT fk_venta_vendedor FOREIGN KEY (id_vendedor) REFERENCES vendedor(id_vendedor),
  CONSTRAINT fk_venta_medio FOREIGN KEY (id_medio) REFERENCES medio_pago(id_medio)
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN EXECUTE IMMEDIATE '
CREATE TABLE detalle_venta (
  id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_venta NUMBER,
  id_producto NUMBER,
  cantidad NUMBER(5) CHECK (cantidad > 0),
  precio_unit NUMBER(10,0) CHECK (precio_unit > 0),
  CONSTRAINT fk_det_venta FOREIGN KEY (id_venta) REFERENCES venta(id_venta),
  CONSTRAINT fk_det_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
)'; EXCEPTION WHEN OTHERS THEN NULL; END;
/





----------------------------------------------------------------
-- 0) REGIÓN  (estructura + datos mínimos con MERGE)
----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE region (
      id_region NUMBER PRIMARY KEY,
      nombre    VARCHAR2(60) NOT NULL
    )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

MERGE INTO region r
USING (
  SELECT 1 id_region, 'Metropolitana' nombre FROM dual UNION ALL
  SELECT 2, 'Valparaíso'  FROM dual UNION ALL
  SELECT 3, 'Biobío'      FROM dual UNION ALL
  SELECT 4, 'Coquimbo'    FROM dual UNION ALL
  SELECT 5, 'Antofagasta' FROM dual
) s
ON (r.id_region = s.id_region)
WHEN NOT MATCHED THEN
  INSERT (id_region, nombre) VALUES (s.id_region, s.nombre);

-- Verificación rápida
SELECT * FROM region ORDER BY id_region;

----------------------------------------------------------------
-- 1) SALUD (estructura + secuencia + datos con MERGE)
----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE salud (
      id_salud NUMBER PRIMARY KEY,
      nombre   VARCHAR2(80) NOT NULL
    )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_salud START WITH 2050 INCREMENT BY 10';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

MERGE INTO salud s
USING (
  SELECT 2050 id_salud, 'Fonasa'    nombre FROM dual UNION ALL
  SELECT 2060,        'Colmena'     FROM dual UNION ALL
  SELECT 2070,        'Banmédica'   FROM dual
) x
ON (s.id_salud = x.id_salud)
WHEN NOT MATCHED THEN
  INSERT (id_salud, nombre) VALUES (x.id_salud, x.nombre);

SELECT * FROM salud ORDER BY id_salud;

----------------------------------------------------------------
-- 2) AFP (estructura + secuencia + trigger + datos con MERGE)
--    Requisito identidad: 210, 216, 222, 228 (+6)
----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE afp (
      id_afp  NUMBER PRIMARY KEY,
      nombre  VARCHAR2(80) NOT NULL
    )';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_afp START WITH 210 INCREMENT BY 6';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER trg_afp_bi
    BEFORE INSERT ON afp
    FOR EACH ROW
    BEGIN
      IF :NEW.id_afp IS NULL THEN
        :NEW.id_afp := seq_afp.NEXTVAL;
      END IF;
    END;';
END;
/

-- Datos base solicitados + PlanVital; 
MERGE INTO afp a
USING (
  SELECT 210 id_afp, 'Habitat'  nombre FROM dual UNION ALL
  SELECT 216,        'Provida'  FROM dual UNION ALL
  SELECT 222,        'Modelo'   FROM dual
) x
ON (a.id_afp = x.id_afp)
WHEN NOT MATCHED THEN
  INSERT (id_afp, nombre) VALUES (x.id_afp, x.nombre);

MERGE INTO afp a
USING (SELECT 'PlanVital' nombre FROM dual) x
ON (a.nombre = x.nombre)
WHEN NOT MATCHED THEN
  INSERT (nombre) VALUES (x.nombre);

SELECT * FROM afp ORDER BY id_afp;

----------------------------------------------------------------
-- 3) VENTA (secuencia + trigger)  Requisito identidad: 5050 (+3)
----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_venta START WITH 5050 INCREMENT BY 3';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE OR REPLACE TRIGGER trg_venta_bi
    BEFORE INSERT ON venta
    FOR EACH ROW
    BEGIN
      IF :NEW.id_venta IS NULL THEN
        :NEW.id_venta := seq_venta.NEXTVAL;
      END IF;
    END;';
END;
/

-- Inserción “dummy” con id 5050 solo si no existe (para evidenciar el patrón)
INSERT INTO venta (id_venta, fecha_venta, id_cliente, id_medio, total)
SELECT 5050, SYSDATE, 1, 1, 10000 FROM dual
WHERE NOT EXISTS (SELECT 1 FROM venta WHERE id_venta = 5050);

SELECT id_venta, fecha_venta, id_cliente, id_medio, total
FROM venta ORDER BY id_venta;

----------------------------------------------------------------
-- 4) RESTRICCIONES EMPLEADO (CHECK y FK)
----------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE empleado
    ADD CONSTRAINT ck_empleado_sueldo_min CHECK (sueldo_base >= 400000)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE empleado
    ADD CONSTRAINT ck_empleado_activo CHECK (activo IN (''S'',''N''))';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE empleado
    ADD CONSTRAINT fk_empleado_salud
    FOREIGN KEY (id_salud) REFERENCES salud(id_salud)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    ALTER TABLE empleado
    ADD CONSTRAINT fk_empleado_afp
    FOREIGN KEY (id_afp) REFERENCES afp(id_afp)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

----------------------------------------------------------------
-- 5) VISTA de apoyo para ventas
----------------------------------------------------------------
CREATE OR REPLACE VIEW vw_venta_totales AS
SELECT v.id_venta,
       SUM(dv.cantidad * dv.precio_unit) AS total_calculado
FROM venta v
JOIN detalle_venta dv ON dv.id_venta = v.id_venta
GROUP BY v.id_venta;
/

----------------------------------------------------------------
-- 6) INFORME 1: Sueldo, bono, descuentos y sueldo líquido
----------------------------------------------------------------
SELECT
  e.id_empleado                                   AS "ID EMPLEADO",
  e.nombre || ' ' || e.ape_paterno || ' ' || e.ape_materno AS "NOMBRE COMPLETO",
  e.sueldo_base                                   AS "SUELDO BASE",
  NVL(e.bono_jefatura, 0)                         AS "BONO JEFATURA",
  (e.sueldo_base * 0.12)                          AS "DESC. AFP (12%)",
  (e.sueldo_base * 0.07)                          AS "DESC. SALUD (7%)",
  (e.sueldo_base + NVL(e.bono_jefatura,0))
    - (e.sueldo_base * 0.12) - (e.sueldo_base * 0.07)
                                                  AS "SUELDO LÍQUIDO",
  s.nombre                                        AS "SALUD",
  a.nombre                                        AS "AFP"
FROM empleado e
JOIN salud s ON s.id_salud = e.id_salud
JOIN afp   a ON a.id_afp   = e.id_afp
ORDER BY e.id_empleado;

----------------------------------------------------------------
-- 7) INFORME 2: Simulación con aumento del 8% en sueldo base
----------------------------------------------------------------
WITH base AS (
  SELECT
    e.id_empleado,
    e.nombre || ' ' || e.ape_paterno || ' ' || e.ape_materno AS nombre_completo,
    e.sueldo_base,
    NVL(e.bono_jefatura,0)                                AS bono,
    (e.sueldo_base * 1.08)                                AS nuevo_base -- +8%
  FROM empleado e
)
SELECT
  b.id_empleado                                   AS "ID EMPLEADO",
  b.nombre_completo                               AS "NOMBRE COMPLETO",
  b.sueldo_base                                   AS "SUELDO BASE",
  b.bono                                          AS "BONO JEFATURA",
  ROUND(b.nuevo_base,0)                           AS "NUEVO BASE (+8%)",
  ROUND(b.nuevo_base * 0.12,0)                    AS "DESC. AFP (12%)",
  ROUND(b.nuevo_base * 0.07,0)                    AS "DESC. SALUD (7%)",
  ROUND((b.nuevo_base + b.bono)
        - (b.nuevo_base * 0.12) - (b.nuevo_base * 0.07),0) AS "LÍQUIDO SIMULADO"
FROM base b
ORDER BY b.id_empleado;

----------------------------------------------------------------
-- 8) REPORTE: Ventas por cliente (resumen)
----------------------------------------------------------------
SELECT
  c.id_cliente,
  c.nombre,
  COUNT(v.id_venta)                AS compras,
  NVL(SUM(vt.total_calculado), 0)  AS monto_total,
  MAX(v.fecha_venta)               AS ultima_compra
FROM cliente c
LEFT JOIN venta v            ON v.id_cliente = c.id_cliente
LEFT JOIN vw_venta_totales vt ON vt.id_venta = v.id_venta
GROUP BY c.id_cliente, c.nombre
ORDER BY monto_total DESC NULLS LAST, nombre;

----------------------------------------------------------------
-- 9) REPORTE: Detalle por producto (una fila por venta)
----------------------------------------------------------------
SELECT
  p.id_producto,
  p.nombre,
  v.id_venta,
  v.fecha_venta,
  dv.cantidad,
  dv.precio_unit,
  (dv.cantidad * dv.precio_unit) AS subtotal
FROM producto p
JOIN detalle_venta dv ON dv.id_producto = p.id_producto
JOIN venta v          ON v.id_venta    = dv.id_venta
ORDER BY p.id_producto, v.fecha_venta, v.id_venta;

-- === Caso 2: CHECK / UNIQUE exactos de la pauta (idempotentes) ===
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE vendedor ADD CONSTRAINT ck_vendedor_comision CHECK (comision BETWEEN 0 AND 0.25)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE producto ADD CONSTRAINT ck_producto_stock_min CHECK (stock_min >= 3)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE proveedor ADD CONSTRAINT uq_proveedor_email UNIQUE (email)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE marca ADD CONSTRAINT uq_marca_nombre UNIQUE (nombre)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE detalle_venta ADD CONSTRAINT ck_detalle_venta_cantidad CHECK (cantidad > 0)';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- === INFORME 1 (pauta): Bonificación y salario simulado ===
SELECT
  e.id_empleado                                  AS "ID EMPLEADO",
  e.nombre || ' ' || e.ape_paterno || ' ' || e.ape_materno AS "EMPLEADO",
  e.sueldo_base                                  AS "SALARIO",
  e.bono_jefatura                                AS "BONIFICACION",
  (e.sueldo_base + e.bono_jefatura)              AS "SALARIO SIMULADO"
FROM empleado e
WHERE e.activo = 'S'
  AND e.bono_jefatura IS NOT NULL
ORDER BY "SALARIO SIMULADO" DESC, e.ape_paterno DESC;

-- === INFORME 2 (pauta): Aumento 8% para sueldos entre 550k y 800k ===
SELECT
  e.nombre || ' ' || e.ape_paterno || ' ' || e.ape_materno AS "EMPLEADO",
  e.sueldo_base                                          AS "SUELDO",
  ROUND(e.sueldo_base * 0.08, 0)                         AS "POSIBLE AUMENTO (8%)",
  ROUND(e.sueldo_base * 1.08, 0)                         AS "SALARIO SIMULADO"
FROM empleado e
WHERE e.sueldo_base BETWEEN 550000 AND 800000
ORDER BY "SUELDO" ASC;

-- === Secuencia EMPLEADO 750, +3 (solo si no existe) ===
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE seq_empleado START WITH 750 INCREMENT BY 3';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


